export const plugins = [
  'appium-device-farm',
  'appium-wait-plugin',
  'appium-dashboard',
  'appium-gestures-plugin',
  'appium-reporter-plugin',
  '@appium/images-plugin',
  '@appium/relaxed-caps-plugin',
  '@appium/execute-driver-plugin',
  'appium-element-flash',
  'appium-ocr-plugin',
  'appium-altunity-plugin',
  'appium-ddlog-plugin',
  'appium-otel-plugin',
];
